[package]
name = "picky-ffi"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
name = "picky"
crate-type = ["staticlib", "cdylib"]
doc = false
test = false
doctest = false

[target.'cfg(windows)'.build-dependencies]
embed-resource = "3.0"

[dependencies]
picky = { path = "../picky/", default-features = false, features = ["ssh", "x509", "time_conversion", "jose", "pkcs12", "pkcs7", "http_timestamp", "putty"] }
picky-asn1 = { path = "../picky-asn1", default-features = false }
picky-asn1-der = { path = "../picky-asn1-der" }
picky-asn1-x509 = { path = "../picky-asn1-x509", features = ["legacy", "zeroize"] }

argon2 = { version = "=0.6.0-rc.8", features = ["rand_core"] }
rand = "0.10"
rand_core = "0.10"

# FFI
diplomat = { git = "https://github.com/irvingoujAtDevolution/diplomat.git", rev = "68bccfd8d61e146673ccdb2b24bd9f89dc25431c" }
diplomat-runtime = { git = "https://github.com/irvingoujAtDevolution/diplomat.git", rev = "68bccfd8d61e146673ccdb2b24bd9f89dc25431c" }

time = "0.3"
hex = "0.4"
serde_json = "1"

# WASM support
[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.4", features = ["wasm_js"] }

# Pin transitive dependencies versions.
# TODO: Remove when stable versions will be released.
blake2 = "=0.11.0-rc.6"
