[workspace]
resolver = "2"
members = [
    "picky",
    "picky-asn1",
    "picky-asn1-der",
    "picky-asn1-x509",
    "picky-krb",
    "ffi",
    "ffi/wasm",
    "picky-server",
    "picky-signtool",
]

[profile.release]
# Configured that way mostly for the wasm build
lto = true
opt-level = "s"
strip = "debuginfo"
