[workspace]
resolver = "2"
members = [
    "picky",
    "picky-asn1",
    "picky-asn1-der",
    "picky-asn1-x509",
    "picky-krb",
    "ffi",
    "picky-server",
    "picky-signtool",
]

[profile.release-opt-size]
inherits = "release"
lto = true
opt-level = "s"
