[workspace]
resolver = "2"

members = [
    "picky",
    "picky-krb",
    "picky-asn1",
    "picky-asn1-der",
    "picky-asn1-x509",
    "picky-signtool",
    "ffi",
]

default-members = [
    "picky",
    "picky-krb",
    "picky-asn1",
    "picky-asn1-der",
    "picky-asn1-x509",
]