[source,http,options="nowrap"]
----
HTTP/1.1 200 OK
Content-Type: application/x-pem-file
Content-Length: 3378

-----BEGIN CERTIFICATE-----
MIIENDCCAhygAwIBAgIFANusRrAwDQYJKoZIhvcNAQELBQAwGjEYMBYGA1UEAwwP
V2F5a0RlbiBSb290IENBMCIYDzIwMTkxMTI2MTQ1ODQ2WhgPMjAyNDExMjQxNDU4
NDZaMBwxGjAYBgNVBAMMEVdheWtEZW4gQXV0aG9yaXR5MIIBIjANBgkqhkiG9w0B
AQEFAAOCAQ8AMIIBCgKCAQEA1JalWnjPbiitRCVVArWO0V4MEO7WNNat+glYW3Uy
yrOD5NPYlMo5a3ToduDFh0ooztj3QaP+p0PCsH887VfHOOReVHMySFRcQ7m3vQYY
ZLYh/Bf/y504AgGPEviunDxQ2+s+u+L8fnEwnBfc4poPC5ysClYrPb0ffOkMrhvx
0n8FAbDpEZF72dpfyJvbtbN1WFxV7S/OlzfBqKuF+B6gAiAoBjvrQ0UphfuhLwlz
MbEyskhxDUysiPaTUNoC7IdH+GYBf/FhW1BqAAzkJlaHoPb+0Z3MiPCwuOcEZzj6
xUoe1MTHRNQG9weZLHGwDw4NEtrLEAaCD+pw9BqN06P46QIDAQABo3sweTAPBgNV
HRMECDAGAQH/AgEBMA4GA1UdDwEB/wQEAwIBrjApBgNVHQ4EIgQgaiJhVrw5Wz2I
jLpxGSgPZ89KyzE1lV3Xp65oCtpLNTswKwYDVR0jBCQwIoAg6Oh78rkBXwdDBzdC
YQ3PJNLXNcEWFrVAAQZEqXouah4wDQYJKoZIhvcNAQELBQADggIBADyBT7OGl5Dm
uGJEGFgO8n6Fl0k3b7N7dpzwlHmCXxXEcGjrOn66ZLJYwX2VSgdtqrLBb31/aO9S
Y3JFfjJ9qGXgbebC6ZDj7UkQZ1udLGUg4BHOZfcBEXNuj5Jplx9a0LeePxD3Hf/0
mYVnVAe+ceTlHUcySLOv6N5qdiQrZkYb95P3S+CglYTHDIS762FzKgnUEo7q/tHo
5C/VzumRa5sXCYGAodyorqOaGzJkmCyso9UyK9oo2aA4Hvhjxu2llHB5GqbxJtox
0cWICaRBrcWnd3ALdzmb+KAZCvFEx+UB3ZcABl5DxSLP27LZUsbhnFI93ZIpVdOQ
ZRSgtvt5YA0h2pIZCJzUd/I1r0axtVYw6Fs0mWcFJgW1wJKC8ud3CpLJ06fDy6Ru
XbpBbfI8t9bfcUtf3oHQ+1eRSMDOmfFC1MYUwhdmDxUCeWTqg+zVypz+Y+ZFkZ7a
z72g3bkw1V8F3wDF0dxWNHjP+l8NfHibHW9tar5NMyIC+OrAf5eodE0wMKGfpCky
zCBoOJmNV0NmDsD0AAP0I5Cf+dd4WXcAcXp0aQ0Vml2QX1VOxAv1c1dOCuUTaOMH
omhW9UQQp9SXoohyRU1PJBObIUjPySSPhDshaXbgs0HjLDM67YXSvgH/XoPJP4k0
qnpsmYKvO0rvO+3q1dltrMCH5mPRtBY3
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIFMTCCAxmgAwIBAgIEW4w9yjANBgkqhkiG9w0BAQsFADAaMRgwFgYDVQQDDA9X
YXlrRGVuIFJvb3QgQ0EwIhgPMjAxOTExMjYxNDU4NDVaGA8yMDI5MTEyMzE0NTg0
NVowGjEYMBYGA1UEAwwPV2F5a0RlbiBSb290IENBMIICIjANBgkqhkiG9w0BAQEF
AAOCAg8AMIICCgKCAgEAs36OKsOA6r5a9wm1wbnjNbu34f72deZBvobXxIl/sEnF
ACuPQmbxbnoR67AZ1ftQq/4jsNngilyhoKo9vDwEMmqmG4Bw9e1x61nUitjcCSQE
MyWL+CJMEGGC0aro1yMIXvu2uitSVIh/GWs2MtMDYnZtR9Q73aFGjITlZPQ/YGJC
FXCX9whkFQ9UTpxrxnyjxtNhQLAZOYwumrtOhmjDDPXYIysuZ8Q3hH1q5wrM0PgO
mcpLqbyuj+ZxUR0x2jStXsiKKcJHob5NEXb8rYo+Rf+8ejrupu/ETqVE5Y3uybb2
JbZJfkLEo48qcFzK43zwM2RmKVKwDc9BY6GsQOJqso4bGXUu7l7pt4WvFNopc3WK
dq1ModwHbcYx9GYvMnX0G5udQqI043Z7kCFlOcJ8gqwtIC26Pph3zb6+NLulyvr/
FRdQYZ8GjifcSD5v0cALEfUosA1uUNiwJ46qoBdTVeCBKcDojDS7/C3r79bINajG
vJl0auwxpDhzXHmtBmDAzqxf1kIU/gIXnIpX8805FjNbZYEGzGxCFfMvSLzuRduc
Sx3gDuw8q5xXMbE94o8gVFa94r18M3KKIHa7yfmgrD1RUswVYb+C/YZnfcEPpLAn
8GSzSeq4yL43vDEsqaHRTPs6IjpdnLew/MR0lqC5T6xOqVlk3Ov2kvWsMenjKlMC
AwEAAaN7MHkwDwYDVR0TBAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAa4wKQYDVR0O
BCIEIOjoe/K5AV8HQwc3QmENzyTS1zXBFha1QAEGRKl6LmoeMCsGA1UdIwQkMCKA
IOjoe/K5AV8HQwc3QmENzyTS1zXBFha1QAEGRKl6LmoeMA0GCSqGSIb3DQEBCwUA
A4ICAQCv1gfRK7YYQMv2ghBHw6q1TEUSc/gxw6Jo6VSX8EEBrWYSwcqohRH/jpQL
4/CAUVjUIC9tpGisWvIfmhC0YMWPTLcDmxYsMYBEp467nuHPM07oNFpJAqWrgOUE
0eQzbHZMAeomFi85RkMpDBlFhjRnOwOXpDmKA1xSmp98aUhuX0uChyHtp9EwHVuk
GQfmazG+C/NN6kmQ79Ls14Gp1m95GTb0pPZLSvxvuKT+BIeDnpNSkPZ5x/jvzBGt
C2cJSZc88JtEUBtopOmnfypSfssEcRBgPYi+DAmXp6Z8Xp+V1S33cDJOdaCq+9e4
GQqU2oe3H9Br113wgsEI2NVYG0B0GaJenKB/9GzZbU2S5SJbuniF3Lx36y1FR9xv
tMEfzwmEn7Zut3DAV4h/jIqCWJ+YX38Jtfz8v8Tw2f0bd6rti64JpO/jSEtu3P39
85hj7W44ShXKCKH66nWgGCklo8RFKIWrl7dxOtiyr/OU6D/zAGTYCb6C1hUc0ogf
SmrDMTX+NUCC8XfEgjC7eoXls3FbTKLM6rp4RuShoSau9nuSUSgz8EoAo3D/Wrpg
/cVwFR+LnediDdhMmuCRFgryBbuPnUYOElxSAz49BJSyrm9Fp0GUpk849GFog0+H
+WRZS+yoWpBOLXiVoudWQT55n3C/G9c5cLFuuUk0By4lORRKQw==
-----END CERTIFICATE-----
----

