[package]
name = "picky-krb"
version = "0.3.0"
authors = ["Devolutions Inc."]
edition = "2021"
rust-version = "1.60"
keywords = ["kerberos", "asn1", "parse"]
categories = ["encoding"]
description = "Encode/decode Kerberos ASN.1 DER structs"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Devolutions/picky-rs"
readme = "README.md"
include = ["src/**/*", "README.md", "CHANGELOG.md"]

[dependencies]
picky-asn1 = { version = "0.5.0", features = ["chrono_conversion"] }
picky-asn1-der = "0.3.1"
serde = { version = "1.0.136", features = ["derive"] }
byteorder = "1.1.0"
thiserror = "1.0.30"
