[source,http,options="nowrap"]
----
HTTP/1.1 200 OK
Content-Type: application/x-pem-file
Content-Length: 1167

-----BEGIN CERTIFICATE-----
MIIDMDCCAhigAwIBAgIEL2PGbjANBgkqhkiG9w0BAQsFADAcMRowGAYDVQQDDBFX
YXlrRGVuIEF1dGhvcml0eTAiGA8yMDE5MTEyNjE0NTg1MFoYDzIwMjAxMTI1MTQ1
ODUwWjAXMRUwEwYDVQQDEwx0ZXN0LldheWtEZW4wggEiMA0GCSqGSIb3DQEBAQUA
A4IBDwAwggEKAoIBAQCnZ/zQHYYnCFInaTyTziHIOkjoZJOHC1X2uDOENY6KuckT
U5lFFRMm1Y1zFWebNJPK71YGpgNEHdD/WBVhxj6VD70AvxrKXpYnDqr8+nULYwCC
LAmHTsd+hLueZw9rhDniRj3c6ZncFX3uWscZQwoaZHHzpPfCugTHC+kA8+B6Jg57
PSmhRk2k/gmRZpynOh2UxfY7JvLSWa1sCUYzEEgeZ6ST9qztUSxIWoX2TLfL9IVI
R7h9tg0+QaIdPEnljUc6WLN2dOP+iYQx8uhEy1LkBgFt2z/FGcU444UXDu3zlFiA
22ttsmlhxPFmtf5sdsiWZi6MYKLqUP3fDXIwkkdPAgMBAAGjezB5MA8GA1UdEwQI
MAYBAQACAQIwDgYDVR0PAQH/BAQDAgGgMCkGA1UdDgQiBCBcLLtTEekzSm6p7PBU
hnvG4E+VbFqNh6Vf2yq+eQpGAjArBgNVHSMEJDAigCBqImFWvDlbPYiMunEZKA9n
z0rLMTWVXdenrmgK2ks1OzANBgkqhkiG9w0BAQsFAAOCAQEAKOX4R4TW7UpdYzA9
S9CQYibDcwqN6T3fjYLENmAyRiB7T4cY8AXap3bwBCA/Ui7qAf+p2FmsWAnE5eqa
HhECBsKMmJqkJyIUOr92BIrxQISN4Y13T50YUihgvwQ/uFj9hLK4m1VOSujiKEXV
7el+aST3ErG1d3voomOi/SLtAUzCkpOh34lyAchybXJ6dM6zKyfwuhhYz0rQESLv
JZIFJFLhKPXVcKi2AOgYMMmAR8MK/NJi9xXegqJMjhL+BWIBZlR6BDTzLJ5jnnPd
2vXad9YXjgXOosB4SxZ8WcMsBSfuUgCtWFmwpwxwqcdIZf3u3Vp6fpPyHfTuSzZC
57bPBQ==
-----END CERTIFICATE-----
----
