----
-----BEGIN CERTIFICATE-----
MIIEGjCCAgKgAwIBAgIEN8NXxDANBgkqhkiG9w0BAQsFADAiMSAwHgYDVQQDDBdj
b250b3NvLmxvY2FsIEF1dGhvcml0eTAeFw0xOTEwMTcxNzQxMjhaFw0yMjEwMTYx
NzQxMjhaMB0xGzAZBgNVBAMMEnRlc3QuY29udG9zby5sb2NhbDCCASIwDQYJKoZI
hvcNAQEBBQADggEPADCCAQoCggEBAMptALdk7xKj9JmFSycxlaTV47oLv5Aabir1
7f1WseAcZ492Mx0wqcJMmT8rVAusyfqvrhodHu4GELGBySo4KChLEuoEOGTNw/wE
MtM6j1E9K7kig1iiuH9nf9oow7OUdix4+w7TWQWpwl1NekKdTtvLLtEGSjmG187C
UqR6fNHYag+iVMV5Umc5VQadvAgva8qxOsPpDkN/E2df5gST7H5g3igaZtxUa3x7
VreN3qJP0+hYQiyM7KsgmdFAkKpHC6/k36H7SXtpzh0NbH5OJHifYsAP34WL+a6l
Ad0VM7UiIRMcLWA8HfmKL3p4bC+LFv5I0dvUUy1BTz1wHpRvVz8CAwEAAaNdMFsw
CQYDVR0TBAIwADAOBgNVHQ8BAf8EBAMCAaAwHQYDVR0OBBYEFCMimIgHf5c00sI9
jZzeWoMLsR60MB8GA1UdIwQYMBaAFBbHC24DEnsUFLz/zmqB5cMCHo9OMA0GCSqG
SIb3DQEBCwUAA4ICAQA1ehZTTBbes2DgGXwQugoV9PdOGMFEVT4dzrrluo/4exSf
qLrNuY2NXVuNBKW4nDA5aD71Q/KUZ8Y8cV9qa8OBJQvQ0dd0qeHmeEYdDsj5YD4E
CycKx9U1ZX5fi6tpSIX6DsietpCnrw4aTgbEOvMeQcuYCTP30Vpt+mYEKBlR/E2V
cl2zUD+67gqppSaC1RceL/8Cy6ZXlPqwmS2zqK9UhYVRKlEww8xSh/9CR9MmIDc4
pHtCpMawcn6Dmo+A+LcKi5v/NIwvSJTei+h1gvRhvEOPcf4VZJMHXquNrxkMsKpu
u7g/AYH7wl2MBaNaxyNlXY5e5OjxslrbRCfDab11YaJEONcBnapl/+Ajr70uVFN0
9tDXyk0EHYf75NiRztgVKclna26zP5qRb0JSYNQJW2kIIBX6DhU7kt6RcauF2hJ+
jLWOF2vsAS8PdEr7vnR1EGOrrcQ3VUgMscNsDqf50YMi2Inu1Kt2t+QSvYs61ON3
9aVpqR67nskdUWzFCVgWQVezM1ZagoOyNp7WjRYl8hJ0YVZ7TRtP8nJOkZ6s046Y
HVWxMuGdqZfd/AUFb9xzzXjGRuuZ1JmSf+VBOFEe2MaPMyMQBeIs3Othz6Fcy6Am
5F6c3It31WYJwiCa/NdbMIvGy1xvAN5kzR/Y6hkoQljoSr1rVuszJ9dtvuTccA==
-----END CERTIFICATE-----
----
