[source,http,options="nowrap"]
----
HTTP/1.1 200 OK
Content-Type: application/x-pem-file
Content-Length: 1167

-----BEGIN CERTIFICATE-----
MIIDMDCCAhigAwIBAgIEZQ7teTANBgkqhkiG9w0BAQsFADAcMRowGAYDVQQDDBFX
YXlrRGVuIEF1dGhvcml0eTAiGA8yMDE5MTEyNjE0NTg1MFoYDzIwMjAxMTI1MTQ1
ODUwWjAXMRUwEwYDVQQDEwx0ZXN0LldheWtEZW4wggEiMA0GCSqGSIb3DQEBAQUA
A4IBDwAwggEKAoIBAQDt/yYLzFybU6Cdw4v6IcVL7bfKYti7sdA9TvcBrPt9Mv09
hPtHYuSWsmRyx+dtNQb9w82XjoqeCeESkB88QXhZCjqyPV67g3ltqp+Bcqsz9AsY
Yxh6J7uUTDVemnsEKwBAVNAfqSSOh2XGBMSSXjrv+YS+2XnYcnvXi7RZevCtgEUw
2xtSHRQRYG1bAWj0DbmEyf4HGDYWaAI4O7unMd/3cM9oTNoG8zOqikL6TTypxzqV
myjxk53o9gy7rjAd3ozAAE6ZjkdccGJnhMyoLVS6z2v205OZini8HvO1N1Mff/dp
Vj3s1rJHEy2JR27gLV60jFa6/tgTDvZjHWbzKpfXAgMBAAGjezB5MA8GA1UdEwQI
MAYBAQACAQIwDgYDVR0PAQH/BAQDAgGgMCkGA1UdDgQiBCD/lCRVFpdOdXVXVtJr
unNDOwb4191QWm40f4Lg6nHIbzArBgNVHSMEJDAigCBqImFWvDlbPYiMunEZKA9n
z0rLMTWVXdenrmgK2ks1OzANBgkqhkiG9w0BAQsFAAOCAQEAjNAx8xKYR7RgQGwq
3CKuo8BK5BojVIqoSJ5b6A5Yn1mRmwArG8uf8H/HKRNoPdnMPzXsW2T0z+gJ4PWR
xaJd2TnJfp3t/45pZZ3BCO1d7OUlrwB97RFurmyqVmR0AaDA3KWFyH6C8fRc/+20
LCP6HGxaZo+tqNVk28E4Kq1YqjFpH3HLE/3jceeXmKqdwyd0miagLiD0TGxY9XgT
fdO/zur70xSDrPhf6DTrfwE60qX7MbNAdqEVkHPdA5WQZeDNZ753BhYEjCU0sLRe
P2SQYS3tIu68v6zUcmjTF5iVYa9bo1YbBRDpAv793oEWRwVsOmwq73HP1BatfWZU
SPmN1w==
-----END CERTIFICATE-----
----
