name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

jobs:
  formatting:
    name: Check formatting
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Check formatting
        shell: pwsh
        run: |
          Write-Host "Check formatting"
          cargo fmt --all -- --check

          if ($LastExitCode -eq 1) {   
            throw "Bad formatting, please run 'cargo +stable fmt --all'"
          }

  check:
    name: check [${{ matrix.os }}]
    runs-on: ${{ matrix.runner }}
    needs: formatting
    strategy:
      fail-fast: false
      matrix:
        os: [ windows, linux ]
        include:
          - os: windows
            runner: windows-2019
          - os: linux
            runner: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Check compilation
        run: cargo check

  test:
    name: test [${{ matrix.os }}]
    runs-on: ${{ matrix.runner }}
    needs: formatting
    strategy:
      fail-fast: false
      matrix:
        os: [ windows, linux ]
        include:
          - os: windows
            runner: windows-2019
          - os: linux
            runner: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: cargo test --features "wincert","ctl","pkcs7","ssh","ec","time_conversion","ctl_http_fetch"

  msrv:
    # Minimum supported Rust version check for published crates.
    # If this break, bump crate version minor number.
    # See https://github.com/Devolutions/picky-rs/issues/89
    name: Check MSRV [${{ matrix.crate }}]
    runs-on: ubuntu-18.04
    needs: formatting
    strategy:
      fail-fast: false
      matrix:
        crate: [ picky-asn1, picky-asn1-der, picky-asn1-x509, picky ]
        include:
          - crate: picky-asn1
            msvc: 1.56
          - crate: picky-asn1-der
            msvc: 1.56
          - crate: picky-asn1-x509
            msvc: 1.56
          - crate: picky
            msvc: 1.56

    steps:
      - uses: actions/checkout@v2

      - name: Configure runner 
        run: |
          set -e
          curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal --default-toolchain ${{ matrix.msvc }}

      - name: cargo check ${{ matrix.crate }}
        run: cargo +${{ matrix.msvc }} check -p picky-asn1
