name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

jobs:
  formatting:
    name: Check formatting
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Check formatting
        shell: pwsh
        run: |
          Write-Host "Check formatting"
          cargo fmt --all -- --check
          cargo fmt --manifest-path ./ffi/wasm/Cargo.toml -- --check

          if ($LastExitCode -eq 1) {   
            throw "Bad formatting, please run 'cargo +stable fmt --all'"
          }

  lints:
    name: Lints [${{ matrix.os }}]
    runs-on: ${{ matrix.runner }}
    needs: formatting
    strategy:
      fail-fast: false
      matrix:
        os: [ windows, linux ]
        include:
          - os: windows
            runner: windows-2019
          - os: linux
            runner: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Run clippy
        run: cargo clippy --locked --workspace --all-features -- -D warnings

  tests:
    name: Tests [${{ matrix.os }}]
    runs-on: ${{ matrix.runner }}
    needs: formatting
    strategy:
      fail-fast: false
      matrix:
        os: [ windows, linux ]
        include:
          - os: windows
            runner: windows-2019
          - os: linux
            runner: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: cargo test --locked --verbose --workspace --all-features

  msrv:
    # Minimum supported Rust version check for published crates.
    # If this break, bump crate version minor number.
    # See https://github.com/Devolutions/picky-rs/issues/89
    name: Check MSRV [${{ matrix.crate }}]
    runs-on: ubuntu-20.04
    needs: formatting
    strategy:
      fail-fast: false
      matrix:
        crate: [ picky-asn1, picky-asn1-der, picky-asn1-x509, picky ]
        include:
          - crate: picky-asn1
            msvc: "1.60"
          - crate: picky-asn1-der
            msvc: "1.60"
          - crate: picky-asn1-x509
            msvc: "1.60"
          - crate: picky
            msvc: "1.60"

    steps:
      - uses: actions/checkout@v2

      - name: Configure runner 
        run: |
          set -e
          curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal --default-toolchain ${{ matrix.msvc }}

      - name: cargo check ${{ matrix.crate }}
        run: cargo +${{ matrix.msvc }} check -p picky-asn1

  lints-wasm:
    name: Lints WASM
    runs-on: ubuntu-20.04
    needs: formatting

    steps:
      - uses: actions/checkout@v2

      - name: Run clippy
        run: cargo clippy --locked --all-features --manifest-path ./ffi/wasm/Cargo.toml -- -D warnings
