name: Publish npm package

on:
  workflow_dispatch:
  schedule:
    - cron: '48 3 * * 1' # 3:48 AM UTC every Monday

jobs:
  publish:
    name: Build and publish npm package
    runs-on: ubuntu-latest
    environment: npm-publish

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.DEVOLUTIONSBOT_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Setup wasm-pack
        shell: bash
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh      

      - name: Tests
        shell: pwsh
        run: |
          Set-Location ./ffi/wasm
          ./run_tests.ps1

      - name: Build & Publish
        if: github.event_name != 'schedule'
        shell: pwsh
        run: |
          Set-Location ./ffi/wasm
          npm config set "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}"
          ./publish.ps1
